set_absolute_position:
  name: Set absolute position
  description: Moves a Sunsa blind to any position from closed backwards to closed forwards.
  target:
    entity:
      integration: sunsa
      device_class: blind
  fields:
    position:
      name: Position
      description: "New position (0: open, -100: closed backwards, 100: closed forwards)."
      required: true
      default: 0
      selector:
        number:
          min: -100
          max: 100